import { useEffect, useState } from 'react';
import { Smartphone, X } from 'lucide-react';
import { createPairingCode, fetchDevices, revokeDevice } from '../api';
import type { PairedDevice, PairingCode } from '../types';
import { sectionLabelStyle } from '../styles';
import { Button } from './Button';

function formatWhen(unix: number | null): string {
  if (!unix) return 'never';
  const d = new Date(unix * 1000);
  const mins = Math.round((Date.now() - d.getTime()) / 60_000);
  if (mins < 2) return 'just now';
  if (mins < 60) return `${mins} min ago`;
  if (mins < 24 * 60) return `${Math.round(mins / 60)} h ago`;
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

function Countdown({ until, onExpire }: { until: number; onExpire: () => void }) {
  const [now, setNow] = useState(() => Date.now() / 1000);
  useEffect(() => {
    const t = window.setInterval(() => setNow(Date.now() / 1000), 1000);
    return () => window.clearInterval(t);
  }, []);
  const left = Math.max(0, Math.round(until - now));
  useEffect(() => {
    if (left === 0) onExpire();
  }, [left, onExpire]);
  return <>{Math.floor(left / 60)}:{String(left % 60).padStart(2, '0')}</>;
}

const codeStyle = {
  fontFamily: 'var(--font-mono)', fontSize: 12.5, color: 'var(--fg-2)', background: 'var(--ink)',
  border: '1px solid var(--hairline)', borderRadius: 4, padding: '6px 8px', display: 'block', userSelect: 'all',
} as const;

/** Desktop-only: pair phones with a QR code and revoke paired passkeys. */
export function DevicesDialog({ remoteHost, onClose }: { remoteHost: string | null; onClose: () => void }) {
  const [devices, setDevices] = useState<PairedDevice[] | null>(null);
  const [pairing, setPairing] = useState<PairingCode | null>(null);
  const [confirmRevoke, setConfirmRevoke] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  function load() {
    fetchDevices().then(setDevices).catch((e) => setError(String(e)));
  }
  useEffect(load, []);

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') { e.stopPropagation(); onClose(); }
    }
    window.addEventListener('keydown', onKey, true);
    return () => window.removeEventListener('keydown', onKey, true);
  }, [onClose]);

  async function startPairing() {
    setError(null);
    try {
      setPairing(await createPairingCode());
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  }

  async function revoke(id: string) {
    try {
      await revokeDevice(id);
      setConfirmRevoke(null);
      load();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  }

  return (
    <div
      onClick={onClose}
      style={{ position: 'fixed', inset: 0, background: 'rgba(0, 0, 0, 0.5)', display: 'flex', alignItems: 'flex-start', justifyContent: 'center', paddingTop: 80, zIndex: 150 }}
    >
      <div
        role="dialog"
        aria-label="Devices"
        onClick={(e) => e.stopPropagation()}
        style={{
          width: 520, maxWidth: 'calc(100vw - 32px)', maxHeight: 'calc(100vh - 120px)', overflowY: 'auto',
          background: 'var(--ink-2)', border: '1px solid var(--hairline)', borderRadius: 8, padding: 24,
          display: 'flex', flexDirection: 'column', gap: 20, boxShadow: '0 16px 48px rgba(0, 0, 0, 0.45)',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center' }}>
          <span style={{ flex: 1, fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 17 }}>Devices</span>
          <button onClick={onClose} title="Close (Esc)" style={{ background: 'transparent', border: 'none', cursor: 'pointer', display: 'flex' }}>
            <X size={16} color="var(--fg-4)" />
          </button>
        </div>

        {!remoteHost ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10, fontSize: 13.5, lineHeight: 1.5, color: 'var(--fg-3)' }}>
            <div>Phone access is off. To use command center from your phone over Tailscale, run these on this computer:</div>
            <code style={codeStyle}>tailscale serve --bg 4287</code>
            <code style={codeStyle}>task config set remote-host &lt;machine&gt;.&lt;tailnet&gt;.ts.net</code>
            <div>Then restart <code style={{ fontFamily: 'var(--font-mono)' }}>task serve</code> and come back here to pair a phone.</div>
          </div>
        ) : pairing ? (
          <div style={{ display: 'flex', gap: 20, alignItems: 'center' }}>
            <div
              aria-label="Pairing QR code"
              style={{ width: 192, height: 192, flex: 'none', borderRadius: 6, overflow: 'hidden', background: 'var(--fg-1)' }}
              // Generated by our own server from the pairing URL.
              dangerouslySetInnerHTML={{ __html: pairing.qr_svg }}
            />
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10, minWidth: 0, fontSize: 13.5, lineHeight: 1.5, color: 'var(--fg-3)' }}>
              <div>Scan with your phone’s camera, then set up Face ID. Your phone must be on your tailnet.</div>
              <div>
                <span style={{ ...sectionLabelStyle, display: 'block', marginBottom: 2 }}>Code</span>
                <span style={{ fontFamily: 'var(--font-mono)', fontSize: 20, letterSpacing: '0.08em', color: 'var(--fg-1)' }}>
                  {pairing.code.slice(0, 4)}-{pairing.code.slice(4)}
                </span>
              </div>
              <div style={{ fontSize: 12, color: 'var(--fg-5)', wordBreak: 'break-all' }}>{pairing.url}</div>
              <div style={{ fontSize: 12, color: 'var(--fg-4)' }}>
                Expires in <Countdown until={pairing.expires_at} onExpire={() => setPairing(null)} /> · single use
              </div>
              <div>
                <Button size="sm" variant="secondary" onClick={() => { setPairing(null); load(); }}>Done</Button>
              </div>
            </div>
          </div>
        ) : (
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{ flex: 1, fontSize: 13.5, lineHeight: 1.5, color: 'var(--fg-3)' }}>
              Phones sign in with a passkey at <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--fg-1)' }}>https://{remoteHost}</span>
            </div>
            <Button size="sm" onClick={startPairing}>Pair a phone</Button>
          </div>
        )}

        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          <div style={sectionLabelStyle}>Paired devices</div>
          {devices && devices.length === 0 && (
            <div style={{ fontSize: 13, color: 'var(--fg-5)', fontStyle: 'italic' }}>No phones paired yet.</div>
          )}
          {devices?.map((d) => (
            <div key={d.id} style={{ display: 'flex', alignItems: 'center', gap: 10, border: '1px solid var(--hairline)', borderRadius: 6, padding: '8px 10px' }}>
              <Smartphone size={16} color="var(--fg-4)" style={{ flex: 'none' }} />
              <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: 2 }}>
                <span style={{ fontSize: 13.5, fontWeight: 600, color: 'var(--fg-1)' }}>{d.name}</span>
                <span style={{ fontSize: 12, color: 'var(--fg-5)' }}>Added {formatWhen(d.created)} · last used {formatWhen(d.last_used)}</span>
              </div>
              {confirmRevoke === d.id ? (
                <>
                  <Button size="sm" variant="secondary" onClick={() => setConfirmRevoke(null)}>Keep</Button>
                  <button
                    onClick={() => revoke(d.id)}
                    style={{ height: 34, padding: '0 14px', borderRadius: 5, border: '1px solid transparent', background: 'var(--danger)', color: 'var(--ink)', fontSize: 13, fontWeight: 600, cursor: 'pointer' }}
                  >
                    Revoke
                  </button>
                </>
              ) : (
                <Button size="sm" variant="secondary" onClick={() => setConfirmRevoke(d.id)}>Revoke</Button>
              )}
            </div>
          ))}
        </div>

        {error && <div style={{ fontSize: 13, color: 'var(--danger)' }}>{error}</div>}
      </div>
    </div>
  );
}
